// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWhjToKsr5wHpUCs0JDNtM-_JAXKJ5LNk',
    appId: '1:44603276985:web:6bbf1b2256373c99f9e568',
    messagingSenderId: '44603276985',
    projectId: 'backtocampus-18ee0',
    authDomain: 'backtocampus-18ee0.firebaseapp.com',
    storageBucket: 'backtocampus-18ee0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAJe_-P2d4ASUBH7qFVSZ4OiqhvVYEefg',
    appId: '1:44603276985:android:7f711b5fd3013a89f9e568',
    messagingSenderId: '44603276985',
    projectId: 'backtocampus-18ee0',
    storageBucket: 'backtocampus-18ee0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABsCJDwPHuH_XZ5yQji-W2otA-E-LEMl0',
    appId: '1:44603276985:ios:7ffcc15c09539788f9e568',
    messagingSenderId: '44603276985',
    projectId: 'backtocampus-18ee0',
    storageBucket: 'backtocampus-18ee0.firebasestorage.app',
    iosBundleId: 'com.example.back2Campus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABsCJDwPHuH_XZ5yQji-W2otA-E-LEMl0',
    appId: '1:44603276985:ios:7ffcc15c09539788f9e568',
    messagingSenderId: '44603276985',
    projectId: 'backtocampus-18ee0',
    storageBucket: 'backtocampus-18ee0.firebasestorage.app',
    iosBundleId: 'com.example.back2Campus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWhjToKsr5wHpUCs0JDNtM-_JAXKJ5LNk',
    appId: '1:44603276985:web:23a6ab4c6634d0eef9e568',
    messagingSenderId: '44603276985',
    projectId: 'backtocampus-18ee0',
    authDomain: 'backtocampus-18ee0.firebaseapp.com',
    storageBucket: 'backtocampus-18ee0.firebasestorage.app',
  );

}